
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author idrieskysia
 */
public class TestTaker extends javax.swing.JPanel {
    ArrayList<TestGenerator.TestQuestion> questions = new ArrayList<TestGenerator.TestQuestion>();
    ArrayList<Boolean> answers = new ArrayList<Boolean>();
    int numberofquestions = 3;
    int index = 0;
    /**
     * Creates new form TestTaker
     */
    TestTaker(int qNumber) {
        
        initComponents();
        TestGenerator.TestQuestion t1 = TestGenerator.GenerateBooleanQuestions(0,10,55);
        questions.add(t1);
//        System.out.println(t1.QNumber + ": "+t1.QQuestion + " is " + t1.QAnswer);
        for (int i  = 0; i< qNumber-1; i++){
            t1 = TestGenerator.GenerateBooleanQuestions(t1.QNumber,10,55);
            questions.add(t1);
//            System.out.println(t1.QNumber + ": "+t1.QQuestion + " is " + t1.QAnswer);
        }
        ReLabel();
    }
    public TestTaker() {
        this(3);
    }

    private void ReLabel(){
        jLabel1.setText("Question " + questions.get(index).QNumber + ":");
        jLabel3.setText(questions.get(index).QQuestion);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Righteous", 0, 18)); // NOI18N
        jLabel1.setText("Question 100:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Banner1.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Righteous", 0, 18)); // NOI18N
        jLabel3.setText("if 13 >= 12 or 45 < 55");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/FalseButton.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                False(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/True Button.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
                True(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(64, 64, 64)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButton1)))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(105, 105, 105)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void False(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_False
        // TODO add your handling code here:
        answers.add(index, new Boolean(false));
        if(index < questions.size()-1){
        index +=1;
        ReLabel();
        }
        else{
//            BooleanApp.swapToMenu();
                BooleanApp.swapToTestResults(questions, answers);
        }
    }//GEN-LAST:event_False

    private void True(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_True
        // TODO add your handling code here:
        answers.add(index, new Boolean(true));
        if(index < questions.size()-1){

            index +=1;
            ReLabel();
        }
        else{
//            BooleanApp.swapToMenu();
                BooleanApp.swapToTestResults(questions, answers);

        }
    }//GEN-LAST:event_True


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
