
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.net.URL;
import java.util.ArrayList;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.StackPane;
import javafx.scene.paint.Color;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author idrieskysia
 */
public class TestTaker2 extends javax.swing.JPanel {
    ArrayList<TestGenerator.TestQuestion> questions = new ArrayList<TestGenerator.TestQuestion>();
    ArrayList<Boolean> answers = new ArrayList<Boolean>();
    int numberofquestions = 3;
    int index = 0;
//    private static JFXPanel fxContainer;
    private static int JFXPANEL_WIDTH_INT = 300;
    private static int JFXPANEL_HEIGHT_INT = 250;
//    final WebView browser = new WebView();
//    final WebEngine webEngine = browser.getEngine();
     
    /**
     * Creates new form TestTaker
     */
    TestTaker2(int qNumber) {

        initComponents();
        TestGenerator.TestQuestion t1 = TestGenerator.GenerateBooleanQuestions(0,10,55);
        questions.add(t1);
//        System.out.println(t1.QNumber + ": "+t1.QQuestion + " is " + t1.QAnswer);
        for (int i  = 0; i< qNumber-1; i++){
            t1 = TestGenerator.GenerateBooleanQuestions(t1.QNumber,10,55);
            questions.add(t1);
//            System.out.println(t1.QNumber + ": "+t1.QQuestion + " is " + t1.QAnswer);
        }
//        jFXPanel1 = new JFXPanel();
//        jFXPanel1.setPreferredSize(new Dimension(JFXPANEL_WIDTH_INT, JFXPANEL_HEIGHT_INT));
//        add(jFXPanel1, BorderLayout.CENTER);
//        final WebView browser = new WebView();
//        final WebEngine webEngine = browser.getEngine();
//        browser.getStylesheets().add("assets/QuestionGenerator/style.css");
//        webEngine.load("assets/QuestionGenerator/example/ExampleTestView.html");
//        Scene sc = new Scene(browser, Color.web("#666970"));
//        jFXPanel1.setScene(sc);
//        browser.getStylesheets().add("webviewsample/BrowserToolbar.css");
        Platform.runLater(new Runnable() {
            
            @Override
            public void run() {
                createScene();
            }
        });
        ReLabel();
        
    }
    private static final String TEST_RESOURCE_NAME = "/assets/QuestionGenerator/example/ExampleTestView.html";
    private void createScene() {
        WebView browser = new WebView();
        WebEngine webEngine = browser.getEngine();
        URL url = TestTaker2.class.getResource(TEST_RESOURCE_NAME);
        webEngine.load(url.toExternalForm());
        StackPane root = new StackPane();
        root.getChildren().add(browser);
        jFXPanel1.setScene(new Scene(root));
    }
    
    
    public TestTaker2() {
        this(3);
    }

    private void ReLabel(){
//        jLabel1.setText("Question " + questions.get(index).QNumber + ":");
//        jLabel3.setText(questions.get(index).QQuestion);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jFXPanel1 = new javafx.embed.swing.JFXPanel();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Banner1.png"))); // NOI18N

        jFXPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton3.setFont(new java.awt.Font("Righteous", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/GenericButton.png"))); // NOI18N
        jButton3.setText("Submit");
        jButton3.setBorder(null);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jFXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(25, 25, 25))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton3;
    private javafx.embed.swing.JFXPanel jFXPanel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
